Dks bak recon 2
mbta/trike pull request #18
Opened 2022-10-20 21:03 UTC by dks-mbta

#### Summary of changes
**Asana Ticket:** [🚲 Better Trike visibility](https://app.asana.com/0/584764604969369/1202976800436270/f)

Log proxy and ranch info periodically, and socket details on connect/disconnect.  
Ignore :ssl_closed.
Upgrade credo.

#### Reviewer Checklist
- [ ] Any new or changed functions have typespecs
- [ ] Tests were added for any new functionality (don't just rely on Lcov)
- [ ] Meets ticket's acceptance criteria

2022-11-02 16:19 UTC, bklebe requested changes
This looks great so far Dan! A few things need to be changed in `start_link` and `init` but they should be pretty small.

Additionally, I think this might benefit from some more tests. Currently we test that it logs `0`, but we don't test that it logs correctly when there are messages in the process's mailbox, which is the case that we're most interested in. What do you think about writing an integration test that pushes a ton of data into Trike with `gen_tcp` and causes an overload, and then makes sure that the health checker is still logging the mailbox size at the expected intervals? You could decrease the interval when testing.

That could also help us check for one of the bugs in the old "staleness checker:" missed checks when the mailbox is full.

2022-11-02 16:19 UTC, bklebe commented on lib/trike/health_checker.ex
> +  end
suggestion (blocking): the `init` callback should validate its options to make sure it has the data needed to initialize the GenServer's state instead of just passing them through. Otherwise, we risk starting the GenServer with invalid state. This could cause a pattern match failure in the `handle_info` callback, which is confusing to debug. Once again, the `StreamConsumer` in RTR is a good example: https://github.com/mbta/rtr/blob/8b2033a1903ece59bf69f00a2fb3875d0ff1035b/rtr/lib/ocs/stream_consumer.ex#L47

2022-11-03 21:55 UTC, dks-mbta commented on lib/trike/health_checker.ex
> +  end
Done. Let me know what you think.

2022-11-03 21:56 UTC, dks-mbta commented on lib/trike/health_checker.ex
> +  end
Done. Let me know what you think.

2022-11-08 18:38 UTC, bklebe commented on lib/trike/health_checker.ex
> +      }
This is still using a map, to build a struct we have to put the struct's name after the percentage: https://elixir-lang.org/getting-started/structs.html#defining-structs.
```suggestion
      state = %__MODULE__{
        ranch_ref: ranch_ref,
        proxy_pid: proxy_pid,
        connection_string: connection_string
      }
```

2022-11-08 18:38 UTC, bklebe commented on lib/trike/health_checker.ex
> +      :ignore
question: do we want to return `:ignore` here or something like `{:stop, {:missing_arg, arg}}` (if we want to see in the logs what arg is missing, or we can just say `{:stop, :missing_arg}`)? According to the docs for `init/1`, returning `:ignore` doesn't cause the parent to terminate: https://hexdocs.pm/elixir/1.14.1/GenServer.html#c:init/1. My inclination is to say we want `{:stop, reason}` here. If the health checker doesn't start properly, we won't know about the state of the proxy.

2022-11-16 20:07 UTC, bklebe approved these changes

2022-11-16 20:19 UTC, dks-mbta commented on lib/trike/health_checker.ex
> +      :ignore
Ok, done.

2022-11-16 20:19 UTC, merged